# Generated by Django 4.2.13 on 2024-06-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('difficulty', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=50)),
            ],
        ),
    ]
